services:
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      .env
    networks:
      - i_network
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    restart:  always

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - i_network
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
    restart:  always
    
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      .env
    ports:
      - "3306"
    networks:
      - i_network
    volumes:
      - mariadb_volume:/var/lib/mysql
    restart:  always

networks:
  i_network:
    driver: bridge

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: 'none'
      device: /home/ajamshid/data/wordpress
      o: bind
  mariadb_volume:
    driver: local
    driver_opts:
      type: 'none'
      device: /home/ajamshid/data/mariadb
      o: bind
